"""Refatoracao da tabela servico para adequar ao modelo ItemCatalogo

obs: Dados de cliente, produtos relacionados ao servico, data de entrega não precisam ser definidos em serviços pois serão definidos no pedido em si.
Revision ID: 6e84f941fd58
Revises: 80ed69fd02a4
Create Date: 2026-05-21 20:54:15.400711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e84f941fd58'
down_revision = '80ed69fd02a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo_estimado', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('servicos_cliente_id_fkey'), type_='foreignkey')
        batch_op.drop_column('data_prevista_entrega')
        batch_op.drop_column('cliente_id')
    
    op.drop_table('servicos_produtos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_prevista_entrega', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('servicos_cliente_id_fkey'), 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('tempo_estimado')

    # ### end Alembic commands ###
