"""Criacao da tabela servico

Revision ID: 80ed69fd02a4
Revises: a5fc3317a323
Create Date: 2026-05-21 20:30:59.559712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ed69fd02a4'
down_revision = 'a5fc3317a323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxas_cartao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=True),
    sa.Column('emitir_nota_fiscal', sa.Boolean(), nullable=False),
    sa.Column('status_pedido', sa.String(length=50), nullable=False),
    sa.Column('status_oficina', sa.String(length=50), nullable=False),
    sa.Column('data_prevista_retirada', sa.DateTime(), nullable=True),
    sa.Column('data_entrega_real', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('data_prevista_entrega', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['itens_catalogo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos_produtos',
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['itens_catalogo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['itens_catalogo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('servico_id', 'produto_id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('item_catalogo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_catalogo_id'], ['itens_catalogo.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('valor_instalacao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('especificacao_1', sa.String(length=255), nullable=True),
    sa.Column('especificacao_2', sa.String(length=255), nullable=True),
    sa.Column('especificacao_3', sa.String(length=255), nullable=True),
    sa.Column('imagem_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id'], ['itens_catalogo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('itens_catalogo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('itens_catalogo_sku_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('itens_catalogo_subcategoria_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('itens_catalogo_categoria_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('itens_catalogo_marca_id_fkey'), type_='foreignkey')
        batch_op.drop_column('observacao')
        batch_op.drop_column('especificacao_2')
        batch_op.drop_column('estoque_atual')
        batch_op.drop_column('especificacao_1')
        batch_op.drop_column('imagem_url')
        batch_op.drop_column('custo_compra')
        batch_op.drop_column('sku')
        batch_op.drop_column('valor_instalacao')
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('estoque_minimo')
        batch_op.drop_column('marca_id')
        batch_op.drop_column('especificacao_3')
        batch_op.drop_column('subcategoria_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_catalogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategoria_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('especificacao_3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marca_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estoque_minimo', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('valor_instalacao', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custo_compra', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('imagem_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('especificacao_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estoque_atual', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('especificacao_2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('itens_catalogo_marca_id_fkey'), 'marcas', ['marca_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('itens_catalogo_categoria_id_fkey'), 'categorias', ['categoria_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('itens_catalogo_subcategoria_id_fkey'), 'subcategorias', ['subcategoria_id'], ['id'], ondelete='SET NULL')
        batch_op.create_unique_constraint(batch_op.f('itens_catalogo_sku_key'), ['sku'], postgresql_nulls_not_distinct=False)

    op.drop_table('produtos')
    op.drop_table('itens_pedido')
    op.drop_table('servicos_produtos')
    op.drop_table('servicos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
