"""Implementacao de Pedidos e Catalogo Polimorfico

Revision ID: a5fc3317a323
Revises: cc858520a6b5
Create Date: 2026-03-23 20:47:19.712411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5fc3317a323'
down_revision = 'cc858520a6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_catalogo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('valor_instalacao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('especificacao_1', sa.String(length=255), nullable=True),
    sa.Column('especificacao_2', sa.String(length=255), nullable=True),
    sa.Column('especificacao_3', sa.String(length=255), nullable=True),
    sa.Column('imagem_url', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.drop_table('produtos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subcategoria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marca_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('valor_venda', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('valor_instalacao', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('custo_compra', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('estoque_atual', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estoque_minimo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('especificacao_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('especificacao_2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('especificacao_3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('imagem_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('produtos_categoria_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], name=op.f('produtos_marca_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], name=op.f('produtos_subcategoria_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('produtos_pkey')),
    sa.UniqueConstraint('sku', name=op.f('produtos_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('itens_catalogo')
    # ### end Alembic commands ###
