"""Add Tabela OrdemServico

Revision ID: c343162c245f
Revises: 6e84f941fd58
Create Date: 2026-05-22 19:15:22.932159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c343162c245f'
down_revision = '6e84f941fd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio_previsto', sa.DateTime(), nullable=False),
    sa.Column('data_termino_previsto', sa.DateTime(), nullable=False),
    sa.Column('data_termino_real', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NA_FILA', 'EM_MANUTENCAO', 'AGUARDANDO_PECA', 'PRONTO', 'ENTREGUE', name='status_os_enum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['itens_catalogo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordens_servico')
    # ### end Alembic commands ###
